In [1]:
import open3d as o3d
import numpy as np
import viser
import torch
from pathlib import Path
from attachment.scripts.aabb_merge import tensor_to_aabbs

server = viser.ViserServer(port=7007)

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


╭─────────────── viser ───────────────╮
│             ╷                       │
│   HTTP      │ http://0.0.0.0:7007   │
│   Websocket │ ws://0.0.0.0:7007     │
│             ╵                       │
╰─────────────────────────────────────╯

In [2]:
early_directions_ends = Path("/workspace/Desktop/RoICalculation/early/ends/")
early_directions_starts = Path("/workspace/Desktop/RoICalculation/early/starts/")
early_directions_origins = Path("/workspace/Desktop/RoICalculation/early/origins/")
early_raw_directions_path = Path("/workspace/Desktop/RoICalculation/early/directions/raw/")
early_encoded_directions_path = Path("/workspace/Desktop/RoICalculation/early/directions/encoded/")
early_normalized_directions_path = Path("/workspace/Desktop/RoICalculation/early/directions/normalized/")

early_raw_positions_path = Path("/workspace/Desktop/RoICalculation/early/positions/raw/")
early_encoded_positions_path = Path("/workspace/Desktop/RoICalculation/early/positions/encoded/")
early_normalized_positions_path = Path("/workspace/Desktop/RoICalculation/early/positions/normalized/")

In [3]:
directions_ends = Path("/workspace/Desktop/RoICalculation/ends/")
directions_starts = Path("/workspace/Desktop/RoICalculation/starts/")
directions_origins = Path("/workspace/Desktop/RoICalculation/origins/")
raw_directions_path = Path("/workspace/Desktop/RoICalculation/directions/raw/")
encoded_directions_path = Path("/workspace/Desktop/RoICalculation/directions/encoded/")
normalized_directions_path = Path("/workspace/Desktop/RoICalculation/directions/normalized/")

raw_positions_path = Path("/workspace/Desktop/RoICalculation/positions/raw/")
encoded_positions_path = Path("/workspace/Desktop/RoICalculation/positions/encoded/")
normalized_positions_path = Path("/workspace/Desktop/RoICalculation/positions/normalized/")

## Early

### Direction

In [4]:
early_directions_ends_files = sorted(list(early_directions_ends.glob("*.pt")))
early_directions_starts_files = sorted(list(early_directions_starts.glob("*.pt")))
early_directions_origins_files = sorted(list(early_directions_origins.glob("*.pt")))
early_raw_directions_files = sorted(list(early_raw_directions_path.glob("*.pt")))
early_encoded_directions_files = sorted(list(early_encoded_directions_path.glob("*.pt")))
early_normalized_directions_files = sorted(list(early_normalized_directions_path.glob("*.pt")))

early_raw_positions_files = sorted(list(early_raw_positions_path.glob("*.pt")))
early_encoded_positions_files = sorted(list(early_encoded_positions_path.glob("*.pt")))
early_normalized_positions_files = sorted(list(early_normalized_positions_path.glob("*.pt")))

### Positions

In [ ]:
early_raw_positions = torch.load(early_raw_directions_files[250]).detach()  # Load the first file to check its structure

early_raw_positions = early_raw_positions.reshape(-1,3)

pcd_early_raw_points = o3d.geometry.PointCloud()
pcd_early_raw_points.points = o3d.utility.Vector3dVector(early_raw_positions.numpy())  # Ensure float64 type


server.scene.add_point_cloud(
    name="/early_raw_positions",
    points=np.asarray(pcd_early_raw_points.points),
    colors=[0,0,0],#np.asarray(pcd.colors),
    point_size=0.0001,
)


PointCloudHandle(_impl=_SceneNodeHandleState(name='/early_raw_positions_2', api=<viser._scene_api.SceneApi object at 0x75e1eaf6ece0>, wxyz=array([1., 0., 0., 0.]), position=array([0., 0., 0.]), visible=True, click_cb=None))

## Last

In [ ]:
last_directions_ends_files = sorted(list(early_directions_ends.glob("*.pt")))
last_directions_starts_files = sorted(list(early_directions_starts.glob("*.pt")))
last_directions_origins_files = sorted(list(early_directions_origins.glob("*.pt")))
last_raw_directions_files = sorted(list(early_raw_directions_path.glob("*.pt")))
last_encoded_directions_files = sorted(list(early_encoded_directions_path.glob("*.pt")))
last_normalized_directions_files = sorted(list(early_normalized_directions_path.glob("*.pt")))

last_raw_positions_files = sorted(list(early_raw_positions_path.glob("*.pt")))
last_encoded_positions_files = sorted(list(early_encoded_positions_path.glob("*.pt")))
last_normalized_positions_files = sorted(list(early_normalized_positions_path.glob("*.pt")))

### Direction

In [6]:
directions_ends_files = sorted(list(directions_ends.glob("*.pt")))
directions_starts_files = sorted(list(directions_starts.glob("*.pt")))
directions_origins_files = sorted(list(directions_origins.glob("*.pt")))

# Values of *_29501.pt

ends    = torch.load(directions_ends_files[0])
starts  = torch.load(directions_starts_files[0])
origins = torch.load(directions_origins_files[0])

# Shapes
print(ends.shape)
print(starts.shape)
print(origins.shape)

torch.Size([4096, 48, 1])
torch.Size([4096, 48, 1])
torch.Size([4096, 48, 3])


In [ ]:
# Origins Visualization

server.scene.add_point_cloud(
    name="/origins_original",
    points=np.asarray(origins.reshape(-1,3).detach()),
    colors=np.asarray([0, 0, 0]),
    point_size=0.01,
    point_shape="circle"
)

PointCloudHandle(_impl=_SceneNodeHandleState(name='/origins_original', api=<viser._scene_api.SceneApi object at 0x75e1eaf6ece0>, wxyz=array([1., 0., 0., 0.]), position=array([0., 0., 0.]), visible=True, click_cb=None))

In [9]:
# Raw Directions
files = sorted(list(raw_directions_path.glob("*.pt")))

test_0 = torch.load(files[0])  # Load the first file to check its structure
original_shape = test_0.shape
test_0 = test_0.reshape(-1,3)

print(np.asarray(test_0.detach()))

[[-0.03506  0.624   -0.7803 ]
 [-0.03506  0.624   -0.7803 ]
 [-0.03506  0.624   -0.7803 ]
 ...
 [ 0.1055  -0.9907   0.08356]
 [ 0.1055  -0.9907   0.08356]
 [ 0.1055  -0.9907   0.08356]]


In [10]:
# Encoded Directions
files = sorted(list(encoded_directions_path.glob("*.pt")))

test = torch.load(files[0])  # Load the first file to check its structure

print(np.asarray(test.detach()))

[[ 0.282   -0.305   -0.3813  ...  0.03284  0.4377  -0.0242 ]
 [ 0.282   -0.305   -0.3813  ...  0.03284  0.4377  -0.0242 ]
 [ 0.282   -0.305   -0.3813  ...  0.03284  0.4377  -0.0242 ]
 ...
 [ 0.282    0.4841   0.04105 ...  0.0465  -0.1178   0.1825 ]
 [ 0.282    0.4841   0.04105 ...  0.0465  -0.1178   0.1825 ]
 [ 0.282    0.4841   0.04105 ...  0.0465  -0.1178   0.1825 ]]


In [11]:
# Normalized Directions
files = sorted(list(normalized_directions_path.glob("*.pt")))

test = torch.load(files[0])  # Load the first file to check its structure

print(np.asarray(test.detach()))

[[[0.4824  0.812   0.10986]
  [0.4824  0.812   0.10986]
  [0.4824  0.812   0.10986]
  ...
  [0.4824  0.812   0.10986]
  [0.4824  0.812   0.10986]
  [0.4824  0.812   0.10986]]

 [[0.2031  0.6255  0.1177 ]
  [0.2031  0.6255  0.1177 ]
  [0.2031  0.6255  0.1177 ]
  ...
  [0.2031  0.6255  0.1177 ]
  [0.2031  0.6255  0.1177 ]
  [0.2031  0.6255  0.1177 ]]

 [[0.315   0.6035  0.04712]
  [0.315   0.6035  0.04712]
  [0.315   0.6035  0.04712]
  ...
  [0.315   0.6035  0.04712]
  [0.315   0.6035  0.04712]
  [0.315   0.6035  0.04712]]

 ...

 [[0.4915  0.07227 0.2412 ]
  [0.4915  0.07227 0.2412 ]
  [0.4915  0.07227 0.2412 ]
  ...
  [0.4915  0.07227 0.2412 ]
  [0.4915  0.07227 0.2412 ]
  [0.4915  0.07227 0.2412 ]]

 [[0.454   0.00586 0.4397 ]
  [0.454   0.00586 0.4397 ]
  [0.454   0.00586 0.4397 ]
  ...
  [0.454   0.00586 0.4397 ]
  [0.454   0.00586 0.4397 ]
  [0.454   0.00586 0.4397 ]]

 [[0.5527  0.00464 0.542  ]
  [0.5527  0.00464 0.542  ]
  [0.5527  0.00464 0.542  ]
  ...
  [0.5527  0.00464 0.542

## Position

In [ ]:
# Raw Positions
files = sorted(list(raw_positions_path.glob("*.pt")))

test = torch.load(files[0]).detach().numpy()  # Load the first file to check its structure

test_copy = test.copy()
original_shape = test.shape

test = test.reshape(-1,3).astype(np.float64)
test_2 = test_copy[:,0,:].astype(np.float64)

pcd_test = o3d.geometry.PointCloud()
pcd_test.points = o3d.utility.Vector3dVector(test)  # Ensure float64 type

pcd_test_2 = o3d.geometry.PointCloud()
pcd_test_2.points = o3d.utility.Vector3dVector(test_2)  # Ensure float64 type

server.scene.add_point_cloud(
    name="/raw_positions",
    points=np.asarray(pcd_test.points),
    colors=[0,0,0],#np.asarray(pcd.colors),
    point_size=0.0001,
)

server.scene.add_point_cloud(
    name="/raw_positions_cut",
    points=np.asarray(pcd_test_2.points),
    colors=[0,0,0],#np.asarray(pcd.colors),
    point_size=0.0001,
)


RuntimeError: 

In [5]:
# Encoded Positions
files = sorted(list(encoded_positions_path.glob("*.pt")))
test = torch.load(files[0])  # Load the first file to check its structure
print(test.shape)
print(np.asarray(test.detach()))

torch.Size([196608, 12])
[[ 0.5483   0.8364   0.917   ...  0.9014   0.781    0.625  ]
 [ 0.5405   0.8413   0.909   ...  0.9717   0.4578   0.889  ]
 [ 0.537    0.8438   0.9062  ...  0.989    0.2974   0.9546 ]
 ...
 [ 0.659   -0.752   -0.991   ... -0.667   -0.9937  -0.11066]
 [-0.02417  0.9995  -0.0483  ...  0.5728  -0.939   -0.344  ]
 [-0.9736  -0.2281   0.4443  ...  0.3142   0.5967  -0.8027 ]]


In [6]:
# Normalized Positions
files = sorted(list(normalized_positions_path.glob("*.pt")))
test = torch.load(files[0])  # Load the first file to check its structure
print(test.shape)
print(np.asarray(test.detach()))

torch.Size([4096, 48, 3])
[[[ 5.9234601e-01  4.5614472e-01  5.7126421e-01]
  [ 5.9084666e-01  4.8289597e-01  5.3784084e-01]
  [ 5.9022683e-01  4.9395463e-01  5.2402401e-01]
  ...
  [ 5.3712130e-01  1.4414277e+00 -6.5976179e-01]
  [ 4.9881828e-01  2.1248035e+00 -1.5135810e+00]
  [ 2.3047096e-01  6.9124756e+00 -7.4953642e+00]]

 [[ 5.2968031e-01  4.1858315e-01  5.6776190e-01]
  [ 5.0041491e-01  4.3098783e-01  5.3001797e-01]
  [ 4.8677087e-01  4.3677109e-01  5.1242107e-01]
  ...
  [-4.3357146e-01  8.2687509e-01 -6.7455542e-01]
  [-1.1480309e+00  1.1297117e+00 -1.5960023e+00]
  [-8.2795830e+00  4.1525507e+00 -1.0793650e+01]]

 [[ 5.6504363e-01  4.0778303e-01  5.7745588e-01]
  [ 5.4529381e-01  4.1882467e-01  5.2909160e-01]
  [ 5.2983117e-01  4.2746946e-01  4.9122602e-01]
  ...
  [ 6.1037540e-02  6.8956071e-01 -6.5677691e-01]
  [-2.0851845e-01  8.4026301e-01 -1.3168777e+00]
  [-1.1301723e+00  1.3555374e+00 -3.5738649e+00]]

 ...

 [[ 6.0967004e-01  8.2464468e-01  4.6054685e-01]
  [ 6.0881871