In [1]:
import open3d as o3d
import numpy as np
import viser
import torch
from pathlib import Path

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [2]:
raw_directions_path = Path("/workspace/Desktop/RoICalculation/directions/raw/")
encoded_directions_path = Path("/workspace/Desktop/RoICalculation/directions/encoded/")
normalized_directions_path = Path("/workspace/Desktop/RoICalculation/directions/normalized/")

raw_positions_path = Path("/workspace/Desktop/RoICalculation/positions/raw/")
encoded_positions_path = Path("/workspace/Desktop/RoICalculation/positions/encoded/")
normalized_positions_path = Path("/workspace/Desktop/RoICalculation/positions/normalized/")

## Direction

In [7]:
# Raw Directions
files = sorted(list(raw_directions_path.glob("*.pt")))

test = torch.load(files[0])  # Load the first file to check its structure

print(np.asarray(test.detach())[0])

[[-0.035   0.6245 -0.7803]
 [-0.035   0.6245 -0.7803]
 [-0.035   0.6245 -0.7803]
 [-0.035   0.6245 -0.7803]
 [-0.035   0.6245 -0.7803]
 [-0.035   0.6245 -0.7803]
 [-0.035   0.6245 -0.7803]
 [-0.035   0.6245 -0.7803]
 [-0.035   0.6245 -0.7803]
 [-0.035   0.6245 -0.7803]
 [-0.035   0.6245 -0.7803]
 [-0.035   0.6245 -0.7803]
 [-0.035   0.6245 -0.7803]
 [-0.035   0.6245 -0.7803]
 [-0.035   0.6245 -0.7803]
 [-0.035   0.6245 -0.7803]
 [-0.035   0.6245 -0.7803]
 [-0.035   0.6245 -0.7803]
 [-0.035   0.6245 -0.7803]
 [-0.035   0.6245 -0.7803]
 [-0.035   0.6245 -0.7803]
 [-0.035   0.6245 -0.7803]
 [-0.035   0.6245 -0.7803]
 [-0.035   0.6245 -0.7803]
 [-0.035   0.6245 -0.7803]
 [-0.035   0.6245 -0.7803]
 [-0.035   0.6245 -0.7803]
 [-0.035   0.6245 -0.7803]
 [-0.035   0.6245 -0.7803]
 [-0.035   0.6245 -0.7803]
 [-0.035   0.6245 -0.7803]
 [-0.035   0.6245 -0.7803]
 [-0.035   0.6245 -0.7803]
 [-0.035   0.6245 -0.7803]
 [-0.035   0.6245 -0.7803]
 [-0.035   0.6245 -0.7803]
 [-0.035   0.6245 -0.7803]
 

In [5]:
# Encoded Directions
files = sorted(list(encoded_directions_path.glob("*.pt")))

test = torch.load(files[0])  # Load the first file to check its structure

print(np.asarray(test.detach()))

[[ 0.282   -0.3054  -0.3813  ...  0.03284  0.4392  -0.02428]
 [ 0.282   -0.3054  -0.3813  ...  0.03284  0.4392  -0.02428]
 [ 0.282   -0.3054  -0.3813  ...  0.03284  0.4392  -0.02428]
 ...
 [ 0.282    0.4841   0.04056 ...  0.04654 -0.1164   0.1825 ]
 [ 0.282    0.4841   0.04056 ...  0.04654 -0.1164   0.1825 ]
 [ 0.282    0.4841   0.04056 ...  0.04654 -0.1164   0.1825 ]]


In [6]:
# Normalized Directions
files = sorted(list(normalized_directions_path.glob("*.pt")))

test = torch.load(files[0])  # Load the first file to check its structure

print(np.asarray(test.detach()))

[[[0.4824  0.8125  0.10986]
  [0.4824  0.8125  0.10986]
  [0.4824  0.8125  0.10986]
  ...
  [0.4824  0.8125  0.10986]
  [0.4824  0.8125  0.10986]
  [0.4824  0.8125  0.10986]]

 [[0.2034  0.626   0.11743]
  [0.2034  0.626   0.11743]
  [0.2034  0.626   0.11743]
  ...
  [0.2034  0.626   0.11743]
  [0.2034  0.626   0.11743]
  [0.2034  0.626   0.11743]]

 [[0.315   0.6035  0.04712]
  [0.315   0.6035  0.04712]
  [0.315   0.6035  0.04712]
  ...
  [0.315   0.6035  0.04712]
  [0.315   0.6035  0.04712]
  [0.315   0.6035  0.04712]]

 ...

 [[0.4915  0.0725  0.241  ]
  [0.4915  0.0725  0.241  ]
  [0.4915  0.0725  0.241  ]
  ...
  [0.4915  0.0725  0.241  ]
  [0.4915  0.0725  0.241  ]
  [0.4915  0.0725  0.241  ]]

 [[0.454   0.00586 0.4395 ]
  [0.454   0.00586 0.4395 ]
  [0.454   0.00586 0.4395 ]
  ...
  [0.454   0.00586 0.4395 ]
  [0.454   0.00586 0.4395 ]
  [0.454   0.00586 0.4395 ]]

 [[0.5527  0.00464 0.5415 ]
  [0.5527  0.00464 0.5415 ]
  [0.5527  0.00464 0.5415 ]
  ...
  [0.5527  0.00464 0.541

## Position

In [6]:
# Raw Positions
files = sorted(list(raw_positions_path.glob("*.pt")))

test = torch.load(files[0]).detach().numpy()  # Load the first file to check its structure

test_copy = test.copy()
original_shape = test.shape

test = test.reshape(-1,3).astype(np.float64)

pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(test)  # Ensure float64 type

server = viser.ViserServer()

server.scene.add_point_cloud(
    name="/raw_positions",
    points=np.asarray(pcd.points),
    colors=[0,0,0],#np.asarray(pcd.colors),
    point_size=0.0001,
)


╭─────────────── viser ───────────────╮
│             ╷                       │
│   HTTP      │ http://0.0.0.0:8080   │
│   Websocket │ ws://0.0.0.0:8080     │
│             ╵                       │
╰─────────────────────────────────────╯

PointCloudHandle(_impl=_SceneNodeHandleState(name='/raw_positions', api=<viser._scene_api.SceneApi object at 0x73969e3d0400>, wxyz=array([1., 0., 0., 0.]), position=array([0., 0., 0.]), visible=True, click_cb=None))

In [5]:
# Encoded Positions
files = sorted(list(encoded_positions_path.glob("*.pt")))
test = torch.load(files[0])  # Load the first file to check its structure
print(test.shape)
print(np.asarray(test.detach()))

torch.Size([196608, 12])
[[ 0.5483   0.8364   0.917   ...  0.9014   0.781    0.625  ]
 [ 0.5405   0.8413   0.909   ...  0.9717   0.4578   0.889  ]
 [ 0.537    0.8438   0.9062  ...  0.989    0.2974   0.9546 ]
 ...
 [ 0.659   -0.752   -0.991   ... -0.667   -0.9937  -0.11066]
 [-0.02417  0.9995  -0.0483  ...  0.5728  -0.939   -0.344  ]
 [-0.9736  -0.2281   0.4443  ...  0.3142   0.5967  -0.8027 ]]


In [6]:
# Normalized Positions
files = sorted(list(normalized_positions_path.glob("*.pt")))
test = torch.load(files[0])  # Load the first file to check its structure
print(test.shape)
print(np.asarray(test.detach()))

torch.Size([4096, 48, 3])
[[[ 5.9234601e-01  4.5614472e-01  5.7126421e-01]
  [ 5.9084666e-01  4.8289597e-01  5.3784084e-01]
  [ 5.9022683e-01  4.9395463e-01  5.2402401e-01]
  ...
  [ 5.3712130e-01  1.4414277e+00 -6.5976179e-01]
  [ 4.9881828e-01  2.1248035e+00 -1.5135810e+00]
  [ 2.3047096e-01  6.9124756e+00 -7.4953642e+00]]

 [[ 5.2968031e-01  4.1858315e-01  5.6776190e-01]
  [ 5.0041491e-01  4.3098783e-01  5.3001797e-01]
  [ 4.8677087e-01  4.3677109e-01  5.1242107e-01]
  ...
  [-4.3357146e-01  8.2687509e-01 -6.7455542e-01]
  [-1.1480309e+00  1.1297117e+00 -1.5960023e+00]
  [-8.2795830e+00  4.1525507e+00 -1.0793650e+01]]

 [[ 5.6504363e-01  4.0778303e-01  5.7745588e-01]
  [ 5.4529381e-01  4.1882467e-01  5.2909160e-01]
  [ 5.2983117e-01  4.2746946e-01  4.9122602e-01]
  ...
  [ 6.1037540e-02  6.8956071e-01 -6.5677691e-01]
  [-2.0851845e-01  8.4026301e-01 -1.3168777e+00]
  [-1.1301723e+00  1.3555374e+00 -3.5738649e+00]]

 ...

 [[ 6.0967004e-01  8.2464468e-01  4.6054685e-01]
  [ 6.0881871